### ISSUE TITLE
Update basically broke the audio fix plugin

### ISSUE THREAD

**Issue by julianpoelmann** [oSumAtrIX/aliucord-plugins#10]
Media controls still show up as normal but the call remains in the call channel instead of the media channel rendering the plugin basically useless. All I did was update it to 1.0.2. 1.0.1 worked. Did I do something wrong?

**Comment by oSumAtrIX** [comment]
I am not sure what you mean, can you elaborate?

**Comment by jryeem** [comment]
the thing updated and it broke.

**Comment by julianpoelmann** [comment]
the newest update fixed it again, your a legend!
