### ISSUE TITLE
Does not play discord call audio through headphones

### ISSUE THREAD

**Issue by posLop** [oSumAtrIX/aliucord-plugins#14]
When i join a call my normal phone audio plays with correct quality and my phone mic works as expexted, however the call audio is sent to my phone instead of my headphones.

The menu to select the audio output device in discord is also buggy.  Ill select an output and it doesnt change anything and when i reopen it sometimes it has nothing selected. 

I am using android 13 and my headphones are the sony wf 1000xm3 earbuds

**Comment by oSumAtrIX** [comment]
Did you check if the compatibility option fixes it

**Comment by posLop** [comment]
Using compatibility mode doesnt change anything it behaves exactly the same

**Comment by posLop** [comment]
I think it was a bug where if i joined a call then connected bt it would still play through phone but i fixed it by just leaving and rejoining after bt was connected
