### ISSUE TITLE
[FixBluetoothAudioQuality] - audio still horrible

### ISSUE THREAD

**Issue by NFLD99** [oSumAtrIX/aliucord-plugins#4]
**Describe the bug**
Enabling the plugin makes no difference to audio quality

**To Reproduce**
1. Enable plugin
2. Join call
3. Play a Media source, YouTube for example
4. Notice audio quality is still horrible

**Expected behavior**
Enabling the plugin restores audio quality

**Screenshots**
N/A

**Aliucord Version**
 Version: APP INFORMATION - 105.12 - BETA (105112) | ALIUCORD 30885D7

**Smartphone (please complete the following information):**
 - Device: Moto G7 power
 - OS: Android
 - Version: 9

**Additional context**
N/A

**Comment by oSumAtrIX** [comment]
Can you include relevant `debug logs` ?
