### ISSUE TITLE
Work well but i got a question

### ISSUE THREAD

**Issue by JonasBBX** [oSumAtrIX/aliucord-plugins#8]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Aliucord Version**
 Version 124.12

**Smartphone (please complete the following information):**
 - Device: Oppo A54 5G
 - Android Version: 12

**Additional context**
This plugin is really amazing and is something I've been looking for, for quite some time. But I was wondering if this is possible outside of aliucord so like for other apps using the microphone such as roblox voice chat for an example which when you connect the Bluetooth headset (Beats Solo Pro³) the audio turns really bad like it normally does with discord without this plugin enabled.

**Comment by oSumAtrIX** [comment]
You would need to modify Roblox or the system API for that. You can also use Xposed Hooks for stuff like this

**Comment by JonasBBX** [comment]
aw man alright thank you
